//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspacioInfinitoDotNet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size Resolucion {
            get {
                return ((global::System.Drawing.Size)(this["Resolucion"]));
            }
            set {
                this["Resolucion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int ProfundidadBits {
            get {
                return ((int)(this["ProfundidadBits"]));
            }
            set {
                this["ProfundidadBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PantallaCompleta {
            get {
                return ((bool)(this["PantallaCompleta"]));
            }
            set {
                this["PantallaCompleta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public float VelocidadRotacionInicial {
            get {
                return ((float)(this["VelocidadRotacionInicial"]));
            }
            set {
                this["VelocidadRotacionInicial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public float VelocidadRotacionFinal {
            get {
                return ((float)(this["VelocidadRotacionFinal"]));
            }
            set {
                this["VelocidadRotacionFinal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float TiempoAceleracionRotacion {
            get {
                return ((float)(this["TiempoAceleracionRotacion"]));
            }
            set {
                this["TiempoAceleracionRotacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Realista")]
        public string FormaDeControl {
            get {
                return ((string)(this["FormaDeControl"]));
            }
            set {
                this["FormaDeControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GeneradorAUsar {
            get {
                return ((string)(this["GeneradorAUsar"]));
            }
            set {
                this["GeneradorAUsar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DibujarLineasMapa {
            get {
                return ((bool)(this["DibujarLineasMapa"]));
            }
            set {
                this["DibujarLineasMapa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int RadioSectoresCercanosADibujarEnMapa {
            get {
                return ((int)(this["RadioSectoresCercanosADibujarEnMapa"]));
            }
            set {
                this["RadioSectoresCercanosADibujarEnMapa"] = value;
            }
        }
    }
}
